name: quincy-sui
version: 0.1.0
summary: a Quincy ui client
description: a Quincy ui client with easy access.

confinement: strict
base: core22
grade: stable

slots:
  dbus-quincy-sui: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: org.bar.quincy_sui # adjust accordingly to your app name and
    
apps:
  quincy-sui:
    command: quincy_sui
    extensions: [gnome] # gnome includes the libraries required by flutter
    plugs:
      - network
      - home
      - desktop
      - network-bind
      - wayland
      - x11
      - unity7
      - network-control
      - gsettings
      - filesystem-support
    slots:
      - dbus-quincy-sui
parts:
  quincy-sui:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application