name: quincy-sui
version: 0.1.0
summary: a Quincy ui client
description: a Quincy ui client with easy access.

confinement: strict
base: core22
grade: stable

slots:
  dbus-quincy-sui: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: org.bar.quincy_sui # adjust accordingly to your app name and
    
apps:
  quincy-sui:
    command: quincy_sui
    extensions: [gnome] # gnome includes the libraries required by flutter
    plugs:
      - network
      - home
      - desktop
      - network-bind
      - wayland
      - x11
      - unity7
      - network-control
      - gsettings
      - system-files
      - screencast-legacy
      - personal-files
      - desktop-legacy
      - block-devices
      - custom-device
      - system-observe
      - removable-media
      - home
      - netlink-audit
      - netlink-connector
      - netlink-generic
      - netlink-route
      - firewall-control
    slots:
      - dbus-quincy-sui
parts:
  quincy-sui:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
    stage-packages:
      - zenity

plugs:
  network-control:
    interface: network-control
  firewall-control:
    interface: firewall-control
  netlink-audit:
    interface: netlink-audit
  netlink-connector:
    interface: netlink-connector
  netlink-generic:
    interface: netlink-generic
  netlink-route:
    interface: netlink-route
  system-observe:
    interface: system-observe